// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwnsmpfgaubnjdrujkxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3bnNtcGZnYXVibmpkcnVqa3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTE0ODEsImV4cCI6MjA1OTA2NzQ4MX0.4OE0nJw5xnl-ChTj-cODUJMiOMabDOUTyj_AXtXeDzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);